apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lemonade-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/fahim-devops/lemonade-devops-assessment-fahim'
    targetRevision: HEAD
    path: 'k8s'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
