name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        docker buildx build --platform linux/amd64 --push -t fahim-devops/lemonade-app:${{ github.sha }} .

    - name: Scan Docker Image for Vulnerabilities
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: myrepo/lemonade-app:${{ github.sha }}

    - name: Static Code Analysis
      uses: SonarSource/sonarcloud-github-action@v1.4
      with:
        projectKey: myproject
        organization: myorg
        sonarToken: ${{ secrets.SONAR_TOKEN }}
